@startuml Updated Domain Model

' Gestion des Utilisateurs
package "Gestion des utilisateurs" {
  class Utilisateur << AR >>{
    -identifiant: UUID
    -motDePasse: String
    -nom: String
    -prenom: String
    -dateNaissance: Date
    -email: String
    +seConnecter(): void
    +seDeconnecter(): void
    +modifierMotDePasse(AncienMotDePasse: String, NouveauMotDePasse: String): void
    +modifierProfil(): void
    +consulterProfil(): void
  }

  class ClientSansAbonnement << VO >> {
    +choisirContenu(): void
    +enregistrerContenu(): void
    +voirDetailsContenu(): void
  }

  class ClientAvecAbonnement << VO >> {
    -dateDebut: Date
    -dateFin: Date
    +consulterHistorique(): void
    +consulterRecommandations(): void
    +consulterCoupDeCoeur(): void
    +visionnerContenuEnIllimite(): void
    +posterCommentaire(contenu: String): void
    +accederForum(): void
    +participerLive(theme: String): void
  }

  class TypeAbonnement << VO >> {
    BASIQUE
    PREMIUM
    FAMILY
  }

  class PreferenceUtilisateur << VO >> {
    -genre: String
    -categorie: String
    -acteur: String
    -realisateur: String
  }
}

' Catalogue de contenu
package "Catalogue de contenu" {
  class Contenu << AR >> {
    -titre: String
    -description: String
    -dateAjout: Date
    -duree: String
    -lien: String
    +visionner(): void
  }

  class Metadonnees << VO >> {
    -genre: String
    -dateDeSortie: Date
  }

  class Serie << VO >> {
    -nombreSaisons: Integer
  }

  class Episode << VO >> {
    -titre: String
    -numero: Integer
    -duree: String
  }

  class Categorie << VO >> {
    FILM
    SERIE
    DOCUMENTAIRE
    SPECTACLE
    EMISSION
  }
}

package "Interaction des utilisateurs" {
  class Interaction << AR >> {
    +posterCommentaire(commentaire: Commentaire): void
    +lireCommentaire(): Commentaire[]
    +participerForum(theme: String): void
    +assisterLive(theme: String): void
  }

  class Commentaire << VO >> {
    -contenu: String
    -date: Date
  }

  class Forum << VO >> {
    -saison: String
  }

  class Live << VO >> {
    -theme: String
  }

  class Moderation {
    +suiviInteractions: String
    +moderer(): void
  }
}

Utilisateur <|-- ClientSansAbonnement
Utilisateur <|-- ClientAvecAbonnement
Contenu "1" *-- "*" Metadonnees
Serie --|> Contenu
Serie "1" *-- "1..*" Episode
Contenu "1" o-- "0..*" Categorie
ClientAvecAbonnement --> TypeAbonnement
ClientAvecAbonnement "1" -- "*" PreferenceUtilisateur
ClientSansAbonnement "1" -- "*" PreferenceUtilisateur

@enduml
